[project]
name = "file-watcher"
readme = "README.md"
version = "0.0.1"
dependencies = [
    "watchdog==3.0.0",
    "memphis-py==1.0.1"

]


[project.urls]
"Repository" = "https://github.com/interactivereduction/run-detection"

[project.scripts]
file_watcher = "file_watcher.file_watcher:main"

[project.optional-dependencies]
formatting = [
    "black==23.7.0"
]

test = [
    "pytest==7.4.0",
    "pytest-cov==4.1.0"
]

code-inspection = [
    "pylint==2.17.4",
    "mypy==1.5.0",
    "file_watcher[test]"
]

dev = [
    "file_watcher[code-inspection]"
]


[tool.setuptools]
packages = ["file_watcher"]
