---
on: push

permissions:
  contents: read

jobs:
  code-inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[code-inspection]

      - name: Run pylint
        run: pylint file_watcher

      - name: Run MyPy
        run: mypy --strict file_watcher
