---
on: push

permissions:
  contents: read

jobs:
  code-inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.1

      - name: Set up python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[code-inspection]

      - name: Run pylint
        run: pylint file_watcher file_watcher_operator/file_watcher_operator.py

      - name: Run MyPy
        run: mypy --strict file_watcher file_watcher_operator
